buEmailFromName 		=>	"Ms. Backups ",
buEmailFromAddr 		=> 	"backups\@stephen-mcgregor.com",

#buEmailToAddrs			=> 	[	"bu\@backups.actuallyprettygood.com",
#					 			"gavriloprincep\@yahoo.com"	],
buEmailToAddrs			=> 	[	"gavriloprincep\@yahoo.com"	],
buCurrArchiveFileListingFile 		=> "/tmp/currBUarchiveFileListing.lst",
buNeverListFilename 	=> "/home/backup/neverBackUp_regExps.lst",
buLocalStoreDir       	=> "/home/backup/remoteBackups_localCopies/",
buHistoryDir 			=> "/home/backup/tobu_buHistory/",
buStandardLinksDir 		=> "/home/backup/tobu_core_bu_links/",
buIndivLinksDir 		=> "/home/backup/tobu_files_links/",
buFilesNoDelAfter 		=> "/home/backup/tobu_files_keepmeAfterBU/",
buFilesDelAfter 		=> "/home/backup/tobu_files_delmeAfterBU/",
buTimeFile 				=> "/tmp/bu/backupTimeFile.tmp",
buTempArchive 			=> "/tmp/bu/buTempArchive.tar",
buTempFileList			=> "/tmp/bu/buTempFileList.txt", 
buPassword 				=> "backupPa55w*rd",
buMinBuFilesAndDirs 	=> 4,
buArchiveMaxSize_K 		=> 7000,			# kilobytes
buStartOfSubLine		=>	"backup: ",
buFileListingHeader		=> "\n\nThis is a tar of *.gz files, not a *.tgz\n\n",
buWorkDir				=> "/tmp/bu/",
buStoreHistFilesToKeep	=> {
							day	=>		9,
							week =>		5,
							month =>	3,
							},
buListingFilesToKeep	=> {
							day	=>		21,
							week =>		8,
							month =>	24,
							},
buAllListingsName		=> "allRecentBackupContentsListings",

