buEmailFromName 		=>	"Ms. Backups ",
buEmailFromAddr 		=> 	"backups\@stephen-mcgregor.com",
buEmailFromAddr 		=> 	"made-up@email-address.com",
buEmailToAddrs			=> [ "someFreeEmailAddress@yahoo-or-gmail-or.com" ],
buNeverListFilename 	=> "/home/backup/neverBackUp_regExps.lst",
buLocalStoreDir       	=> "/home/backup/remoteBackups_localCopies/",
buHistoryDir 			=> "/home/backup/tobu_buHistory/",
buStandardLinksDir 		=> "/home/backup/tobu_core_bu_links/",
buIndivLinksDir 		=> "/home/backup/tobu_files_links/",
buFilesNoDelAfter 		=> "/home/backup/tobu_files_keepmeAfterBU/",
buFilesDelAfter 		=> "/home/backup/tobu_files_delmeAfterBU/",
buTimeFile 				=> "/tmp/bu/backupTimeFile.tmp",
buTempArchive 			=> "/tmp/bu/buTempArchive.tar",
buTempFileList			=> "/tmp/bu/buTempFileList.txt", 
buPassword 				=> "zzz---password-here---zzz",
buMinBuFilesAndDirs 	=> 4,
buArchiveMaxSize_K 		=> 7000,			# kilobytes
buStartOfSubLine		=>	"backup: ",
buFileListingHeader		=> "\n\nThis is a tar of *.gz files, not a *.tgz\n\n",
buWorkDir				=> "/tmp/bu/",
buStoreHistFilesToKeep	=> {
							day	=>		9,
							week =>		5,
							month =>	3,
							},
buListingFilesToKeep	=> {
							day	=>		21,
							week =>		8,
							month =>	24,
							},
buAllListingsName		=> "allRecentBackupContentsListings",

